### ISSUE TITLE
Optimize Action Error

### ISSUE THREAD

**Issue by joaocrsousa** [justcoded/just-image-optimizer#12]
When I click on the button "Optimize Now" the console throws an error "POST …/wp-admin/admin-ajax.php 500 (Internal Server Error)". Any idea what might be causing this issue? Thanks

**Comment by joaocrsousa** [comment]
Updating to php 7.1.13 solved this issue but now none of the images are optimized "0.00% saved (0)"

**Comment by aprokopenko** [comment]
Hi, thanks for your feedback.

Would be great if you can check apache error logs, so we can take a look on 500 error and fix it in future releases.

Could you please check that inside database you have 3 new datatables:
wp_image_optimize
wp_image_optimize_log
wp_image_optimize_log_details

Another user reported, that first table is missing. And he has similar error - optimization status is always 0. It can be some problem with WP dbDelta function, which should create tables.

**Comment by joaocrsousa** [comment]
Hi, the errors with the version 5.6.30 of php are the following:

[23-Apr-2018 14:39:20 UTC] PHP Catchable fatal error:  Argument 1 passed to JustCoded\WP\ImageOptimizer\models\Media::get_queued_image_sizes() must be an instance of JustCoded\WP\ImageOptimizer\models\int, integer given, called in …/wp-content/plugins/just-image-optimizer/models/Log.php on line 144 and defined in …/wp-content/plugins/just-image-optimizer/models/Media.php on line 535
[23-Apr-2018 14:39:50 UTC] PHP Catchable fatal error:  Argument 1 passed to JustCoded\WP\ImageOptimizer\models\Media::get_queued_image_sizes() must be an instance of JustCoded\WP\ImageOptimizer\models\int, integer given, called in …/wp-content/plugins/just-image-optimizer/models/Log.php on line 144 and defined in …/wp-content/plugins/just-image-optimizer/models/Media.php on line 535

—

As for the tables, yes the three are in my database but both columns "bytes_before" and "bytes_after" have always the same values, and I'm not compressing the images with anything else.

Thanks!

**Comment by aprokopenko** [comment]
`bytes_after` updated after success optimization, so it's normal that they are equal.

Could you please check Dashboard > Media > Just Image Optimizer > Log tab.
Screenshot of this page and some log details (press on ID to see details) will be great.

**Comment by joaocrsousa** [comment]
Yes, sure. 

<img width="1401" alt="screen shot 2018-04-23 at 15 53 21" src="https://user-images.githubusercontent.com/11942144/39134635-f503de84-470e-11e8-9015-7678c6f875e3.png">

![screen-shot-2018-04-23-at-15 53 45](https://user-images.githubusercontent.com/11942144/39134658-040279ae-470f-11e8-90bd-f9948ed35a6f.png)

**Comment by aprokopenko** [comment]
Does your project accessible from web? (In other words, can Google see your site)?

It use Google Page Speed to optimize the site, but site should be accessible to be validated by this service. Try to use this link: http://prntscr.com/j91jyh inside Google Page Speed test.
If it can provide some results - then we will need to investigate it in more details.

**Comment by joaocrsousa** [comment]
No, it's still being developed in a local environment. Is this the issue? It needs to be online?

**Comment by aprokopenko** [comment]
Yes, you should be online to use it. It's a limitation of Google Page Speed service.

I think I need to update the documentation and add notice on settings page about this. 

Sometimes you think that something is too trivial and don't take any attention to it, so we forgot to add this important information to our docs :(

**Comment by joaocrsousa** [comment]
Ok, thanks for letting us know, I'll run some tests and I will provide you more feedback.
Good luck with the php 5.x error and thanks for your support!

**Comment by aprokopenko** [comment]
I quickly checked the code, it will be a big update to fully support PHP 5.*. 
Our default support is usually php7+. It's also recommended by official WordPress docs.
So I will add this in plugin requirements and notify users in WP admin about that.

Thanks for reporting issues.

**Comment by aprokopenko** [comment]
Added more detailed requirements notice on plugin Dashboard and Settings pages.
