### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by dfeuster** [justcoded/just-image-optimizer#15]
Please change the filename of README.txt to README.md. Yo put all the work into writing that up in markdown you may as well let the world see it that way!

**Comment by aprokopenko** [comment]
It's not a markdown. This is a syntax of WordPress readme file (it follows some markdown syntax).

and this file is required by WordPress.

as a suggestion, it's better to have readme.md as well with nice description. 

However, Google will stop its Optimization API in May 2019, so this plugin will stop working. We're researching for other ways of optimization now. And if we find something - we will update it. If not -we will close it.
